### ISSUE TITLE
QR code for electrum desktop?

### ISSUE THREAD

**Issue by Nugetzrul3** [sugarchain-project/electrum-sugar#2]
I wanted to import my PC's electrum to my phone's electrum, but when I tapped the camera option, the app just crashed

**Comment by cryptozeny** [comment]
thanks to report bug. could you post the error screenshot? or log?

**Comment by Nugetzrul3** [comment]
o wth now its working xD. maybe it was becos it was still syncing blocks. I will close issue now

**Comment by cryptozeny** [comment]
are you sure that no problem at all?

**Comment by cryptozeny** [comment]
@y-chan could you confirm?

**Comment by Nugetzrul3** [comment]
ye there is no problem now.

**Comment by cryptozeny** [comment]
yep but sometimes it can be occur again. you should not closing this issue. i will check it.

**Comment by cryptozeny** [comment]
i think it verifying too much blocks at startup. so it uses cpu 100% and it makes some issues. IMHO.

**Comment by Nugetzrul3** [comment]
Is there a way to get qr code from desktop electrum, can't seem to find the option

**Comment by Nugetzrul3** [comment]
I had to copy all the private codes and send them to myself.

**Comment by Nugetzrul3** [comment]
Network also seems to be not working for desktop and mobile @y-chan

**Comment by Nugetzrul3** [comment]
![Annotation 2019-09-15 220138](https://user-images.githubusercontent.com/52128634/64921294-e41bb280-d804-11e9-8e00-afadba92adbc.png)
